<div class="more-container">
	<a class="close-toggle" href="#" onClick="$('.toggle-container').css('left','100%;')">FERMER</a>
    <h2>En savoir plus sur SpaceClaimSMOPlus</h2>
    <div>
    	<h3>Historique et création de SpaceClaimSMOPlus</h3>
    	<p>SpaceClaimSMOPlus est basé sur SpaceClaim Engineer qu’il intègre complètement en y ajoutant l’expertise Tôlerie de catalCAD acquise depuis 30 ans.</p>
        <p>SpaceClaim , une nouvelle CAO 3D très innovante qui s’impose de plus en plus  jour après jour, est le fruit d'experts tels que Michael Payne et Daniel Dean. Ces pères de la CAO « basée fonctions » (features based) ont déjà connu des succès planétaires énormes quand ils ont lancé le logiciel Pro/Engineer puis SolidWorks. Aujourd'hui, avec SpaceClaim, ils brisent le joug de l'historique de construction pour offrir une CAO 3D sans contrainte et accessible par tous. Avec  de nombreuses fonctionnalités avancées de modélisation mécanique, ils ont associé des fonctionnalités de grandes réputations pour répondre également aux spécificités Tôlerie. Pour ce faire, ils ont choisi cataCAD, qui, forte de ses 30 années d'expérience dans le domaine de la CFAO tôlerie et de son savoir – faire, a donné naissance à SpaceClaimSMOPlus, la version experte Tôlerie sans limite du logiciel SpaceClaim.</p>
    </div>
    <div>
    	<h3>La révolution de la philosophie 3D</h3>
    	<p>SpaceClaim, le logiciel de la société éponyme créée en 2005 par les fondateurs de PTC et SolidWorks offre une modélisation 3D accessible à tous. En effet, les avantages de la conception 3D étaient réservés aux seuls opérateurs formés à l'utilisation de CAO. Ces CAO classiques étaient souvent trop complexes pour quitter les bureaux d’études.... Dès lors, les fonctionnalités de ces logiciels restent inaccessibles à la majorité des personnes qui contribuent directement au développement, à l'industrialisation et à la fabrication des produits conçus avec une CAO. C'est souvent le cas des services méthodes et fabrication qui travaillent non pas sur la CAO 3D sources mais sur des fichiers 2D avec une vue 3D inaccessible (simple viewer) du 3D. </p>
		<p>C'est pourquoi, afin que toutes les personnes travaillant en amont ou en aval du Bureau d’études puissent partager leurs idées sur les modèles 3D, la compagnie SpaceClaim a mis au point une nouvelle génération de CAO. Ils ont créé un modeleur 3D que l’on appelle « Modélisation Directe » ou « Direct Modeling » qui permet une modification d'un modèle 3D sans se soucier de comment le modèle a été créé. Pour comprendre ce que cela signifie, il faut d'abord se rappeler que pour concevoir une pièce, les modeleurs 3D traditionnels (Pro/Engineer, CATIA, SolidWorks, etc.) se basent sur une succession de fonctions (features) qui sont empilées les unes sur les autres, souvent représentées sous la forme d'un arbre, et chaque fonctionnalité successive forme ainsi l'historique de la création d'un modèle 3D.</p>
		<p>Aussi, pour pouvoir effectuer des modifications, il faut d'abord comprendre qu’elle a été la logique de construction utilisée dans l'empilage de ces fonctions. Au contraire, avec SpaceClaim, aucun historique d’opérations utilisées n’est  conservé, ni la méthode, ni la méthodologie de construction, n’ayant aucun effet. Seul le résultat compte pour obtenir la géométrie souhaitée. En outre, à cela s'ajoute la facilité de se familiariser avec le logiciel. Le logiciel bénéficie des dernières fonctionnalités de Windows. Il reprend  l'interface graphique de Windows. Plus encore, l'interface utilisateur est ultra simple.</p>
		<p>En effet,  avec seulement deux icônes (tirer et déplacer) l’intégralité du travail de modélisation et modification est effectuée et ce, avec l'apparence de Microsoft Office dont il utilise les mêmes commandes de raccourci clavier.  Tous ces points contribuent largement à ce que même un novice soit capable de l’utiliser et qu’après quelques minutes d’apprentissage puisse déjà être performant sur les fonctions de base.</p>
    </div>
    <div>
    	<h3>CAO ouverte  et communicante </h3>
        <p>SpaceClaimSMOPlus  est aussi dédiée à la modification des fichiers CAO venant d'autres modeleurs.  Ces modeleurs ont de nombreux formats natifs (SolidWorks, Pro/Engineer, CATIA v4 et v5, Unigraphics, inventor, Solid Edge,..).  Ces formats, ainsi que des formats neutres, utilisables avec la plupart des modeleurs sur le marché (Step, Iges, SAT, XMT), sont pris en charge par le logiciel. C'est dans ce domaine que la technologie de modélisation directe offre le meilleur du meilleur. L'utilisateur n'est plus contraint par une conception paramétrique classique et peut utiliser les fonctions simples présentées par les deux outils de modification principaux : tirer et déplacer. L'environnement extrêmement adaptatif de conception permet de prendre le contrôle de tous les aspects de la conception et de réaliser des modifications qui n'étaient pas prévues à l'avance. Le système interprète de plusieurs façons l'intention de l'utilisateur en reconnaissant quelle géométrie est sélectionnée et dans quel contexte. Il suffit ensuite de tirer sur cette géométrie sélectionnée pour la redimensionner sans être inquiété sur les autres éléments non sélectionnés qui suivront automatiquement le mouvement.</p>
		<p>Par ce moyen, l'opération à effectuer est déterminée sans avoir à passer par une multitude de menus déroulants, des boîtes de dialogue ou de clics par l'utilisateur. Tous les types de modifications, sans exception, qu'ils soient dimensionnels ou structurels, deviennent possibles. Rappelons- nous que ceci n’est pas le cas des autres modeleurs basés fonctions qui ne peuvent pas diviser un solide en plusieurs éléments.</p>
    </div>
    <div>
    	<h3>Conception descendante </h3>
    	<p>La conception descendante, rendue possible par cette nouvelle technologie de modélisation directe, est un autre point fondamental qui distingue là encore ce logiciel des autres.</p>
        <p>L'espace de travail intégré pour les composants (pièces) et ensembles permet la conception à plusieurs niveaux, ce qui permet à l'utilisateur de diviser et fusionner les composants et modifier la structure d'assemblage selon les besoins. Ainsi, un modèle solide peut être divisé en autant d'éléments qui sont nécessaires pour le processus de fabrication optimale, tout en gardant une association parfaite entre chaque élément. Ceci est possible car le système n'est pas « coincé » par un arbre d’historique de construction. Grâce à cette nouvelle génération de modeleur, la productivité des utilisateurs est considérablement améliorée,  SpaceClaim permettant une rapidité de conception et de modification inégalée.</p>
    </div>
    <div>
    	<h3>Le dépliage : Le plus exact et complet du marché</h3>
    	<p>Quand il s'agit de la mise à plat, SpaceClaimSMOPlus calcule automatiquement la mise à plat exacte en prenant en compte les propriétés de la matière qui sera utilisée pour la fabrication ainsi que son épaisseur mais aussi les propriétés technologiques du pliage. L’obtention de la mise à plat exacte est le résultat de l'association d'un algorithme ultra sophistiqué (résultat de 20 années d'expérience de cataCAD) et de la prise en compte d’outils de pliage (poinçons et matrices) qui seront utilisés pour le pliage en fabrication en appelant des tables personnalisables dans un fichier Excel (fichiers .csv).</p>
        <p>Cette personnalisation garantit à chaque utilisateur la conformité du dépliage avec les outils de production, sans aucune erreur possible.</p>
    </div>
    <div>
    	<h3>Pas de mode « Tôle » spécifique</h3>
    	<p>Il est tout aussi remarquable que SpaceClaimSMOPlus se distingue des autres systèmes par l’utilisation d’outils spécifiques  de conception tôlerie qui ne génèrent pas un modèle Tôlerie qui ne serait plus accessible par les outils de modélisation mécanique générale de SpaceClaim.</p>
        <p>Au contraire, les outils généraux de SpaceClaim deviennent complémentaires et peuvent servir de toute manière à n'importe quel stade du développement du projet.</p>
    </div>
    <div>
    	<h3>Réelle associativité bidirectionnelle 2D/3D </h3>
    	<p>Ce point est d’autant plus intéressant qu’il permet de satisfaire les besoins  non communs entre la conception et les traitements méthodes  des fichiers pièces qui se font habituellement en 2D.</p>
        <p>En d'autres termes, les outils de modélisation et de modification de SpaceClaimSMOPlus restent accessibles en 2D. Ainsi, à partir d'une vue 2D ou d’une vue de la coupe transversale, il est possible d'évoluer dans un dessin 3D. Cette modification est instantanément reprise et la mise à plat associée est immédiatement disponible. En addition, cette fonctionnalité est tout aussi précieuse en travaillant sur le déplié lui-même.</p>
        <p>Pour connaître plus en détail les avantages principaux de SpaceClaimSMOPlus sur les CAO traditionnelles, cliquez s’il vous plait sur le lien ci-dessous afin de lire ou télécharger le document PDF approprié.</p>
    </div>
    <div>
    	<h3>Pourquoi choisir SpaceClaimSMOPlus ?</h3>
    	<p>SpaceClaimSMOPlus est Le logiciel CAO Tôlerie le plus complet, simple et intuitif du marché. C’est la CAO Tôlerie sans limite.</p>
        <p>Que ce soit en conception ou travail méthodes sur des modèles importés, n’hésitez plus et foncez.</p>
        <p>En effet, grâce à la nouvelle technologie de modélisation directe, plus besoin d’entamer une réflexion préalable sur le comment on va réaliser sa conception ni de passer un temps fou à comprendre la conception d’un autre en essayant tant bien que mal de décrypter  l’arbre de construction des modèles importés.</p>
        <p>L’arbre de construction est mort. Fini l’arbre de douleur comme le nomme aujourd’hui son propre inventeur, Michael Payne pour Pro/E et SolidWorks.</p>
        <p>Enfin une conception libre. Enfin une CAO ouverte permettant l’exploitation directe sans limite des modèles importés d’autres CAO.</p>
    </div>
</div>